variables:
  PROD_ENV_URL: "https://api.terenuri.md"

stages:
  - deploy
  - clear

prod-deploy:
  stage: deploy
  before_script:
    - date
  script:
    - docker-compose -f docker-compose.yml -p terenuri.md-api up --build -d
  rules:
    - if: ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH)

prod_clear:
  stage: clear
  script:
    - CONTAINERS=$(docker ps -a -q -f status=exited -f status=dead)
    - if [ ${CONTAINERS} ]; then docker rm -v ${CONTAINERS}; fi
    - docker image prune -a -f
  rules:
    - if: ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH)