version: '3'

services:
  app:
    build:
      context: .
      args:
        - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
        - DEBUG=${DEBUG}
        - SECRET_KEY=${SECRET_KEY}
        - DB_PSQL_NAME=${DB_PSQL_NAME}
        - DB_PSQL_USER=${DB_PSQL_USER}
        - DB_PSQL_PASSWORD=${DB_PSQL_PASSWORD}
        - DB_PSQL_HOST=${DB_PSQL_HOST}
        - DB_PSQL_PORT=${DB_PSQL_PORT}
        - DEBIAN_FRONTEND=noninteractive
    image: "chat-api:latest"
    container_name: "chat-api"
    entrypoint: /usr/src/app/entrypoint.sh
    volumes:
      - /home/chat-api/static:/usr/src/app/static # Static Sync
      - /home/chat-api/media:/usr/src/app/media # Media Sync
      - /home/chat-api/logs:/usr/src/app/logs # Media Sync
    ports:
      - 8209:8000
    env_file:
      - .env
  cron:
    build:
      context: .
      args:
        - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
        - DEBUG=${DEBUG}
        - SECRET_KEY=${SECRET_KEY}
        - DB_PSQL_NAME=${DB_PSQL_NAME}
        - DB_PSQL_USER=${DB_PSQL_USER}
        - DB_PSQL_PASSWORD=${DB_PSQL_PASSWORD}
        - DB_PSQL_HOST=${DB_PSQL_HOST}
        - DB_PSQL_PORT=${DB_PSQL_PORT}
        - DEBIAN_FRONTEND=noninteractive
    image: "chat-api:latest"
    container_name: "chat-api-cron"
    entrypoint: ["cron", "-f", "&&", "tail", "-f", "/var/log/cron"]
    volumes:
      - /home/chat-api/static:/usr/src/app/static # Static Sync
      - /home/chat-api/media:/usr/src/app/media # Media Sync
      - /home/chat-api/logs:/usr/src/app/logs # Media Sync
    env_file:
      - .env
  nginx:
    image: nginx
    container_name: "chat-api-api-nginx"
    volumes:
      - /home/chat-api/static:/usr/share/nginx/html/static # Static Sync
      - /home/chat-api/media:/usr/share/nginx/html/media # Media Sync
    ports:
      - "8210:80"
    depends_on:
      - app
